/*
====================================================
Database Schema
====================================================

Database Name:
ecommerce

Tables:

customers
orders
products
payments
order_items
sellers
geolocation

NOTE:

The schema is automatically generated by

notebooks/Data_Import_to_MySQL.ipynb

using pandas dtype inference.

Every execution recreates the database tables from
the original CSV files to avoid duplicate records.
*/